spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://db-host:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${spring.cloud.vault.database.username}
    password: ${spring.cloud.vault.database.password}

  cloud:
    vault:
      uri: http://localhost:8200
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: jjwt
      database:
        enabled: true
        role: springboot-db-role
